# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Usuario\Desktop\primer_proyecto\PyQt5\listas\proyecto1\lista_lista.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(384, 449)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 351, 411))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lb_nombreitem = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lb_nombreitem.setObjectName("lb_nombreitem")
        self.horizontalLayout.addWidget(self.lb_nombreitem)
        self.nombre = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.nombre.setObjectName("nombre")
        self.horizontalLayout.addWidget(self.nombre)
        self.agregar = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.agregar.setObjectName("agregar")
        self.horizontalLayout.addWidget(self.agregar)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lista_izq = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.lista_izq.setObjectName("lista_izq")
        self.horizontalLayout_4.addWidget(self.lista_izq)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_derecha = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_derecha.setObjectName("btn_derecha")
        self.verticalLayout_2.addWidget(self.btn_derecha)
        self.regresar = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.regresar.setObjectName("regresar")
        self.verticalLayout_2.addWidget(self.regresar)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.lista_derecha = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.lista_derecha.setObjectName("lista_derecha")
        self.horizontalLayout_4.addWidget(self.lista_derecha)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.editar = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.editar.setObjectName("editar")
        self.horizontalLayout_2.addWidget(self.editar)
        self.eliminar = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.eliminar.setObjectName("eliminar")
        self.horizontalLayout_2.addWidget(self.eliminar)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lb_nombreitem.setText(_translate("MainWindow", "Nombre Item"))
        self.agregar.setText(_translate("MainWindow", "Agregar"))
        self.btn_derecha.setText(_translate("MainWindow", ">>"))
        self.regresar.setText(_translate("MainWindow", "<<"))
        self.editar.setText(_translate("MainWindow", "Editar"))
        self.eliminar.setText(_translate("MainWindow", "Eliminar"))
