# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Usuario\Desktop\primer_proyecto\PyQt5\tp_noviembre\tabla_archivo_csv.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(896, 187)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabla = QtWidgets.QTableWidget(self.centralwidget)
        self.tabla.setGeometry(QtCore.QRect(10, 10, 481, 161))
        self.tabla.setObjectName("tabla")
        self.tabla.setColumnCount(0)
        self.tabla.setRowCount(0)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(510, 10, 371, 161))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.lbl_nombre = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_nombre.setObjectName("lbl_nombre")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_nombre)
        self.txt_nombre = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.txt_nombre.setObjectName("txt_nombre")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txt_nombre)
        self.lbl_apellido = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_apellido.setObjectName("lbl_apellido")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbl_apellido)
        self.txt_apellido = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.txt_apellido.setObjectName("txt_apellido")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txt_apellido)
        self.lbl_mail = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_mail.setObjectName("lbl_mail")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lbl_mail)
        self.txt_e_mail = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.txt_e_mail.setObjectName("txt_e_mail")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txt_e_mail)
        self.verticalLayout_7.addLayout(self.formLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_agregar = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_agregar.setObjectName("btn_agregar")
        self.horizontalLayout_2.addWidget(self.btn_agregar)
        self.btn_carga = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_carga.setObjectName("btn_carga")
        self.horizontalLayout_2.addWidget(self.btn_carga)
        self.btn_guardar = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_guardar.setObjectName("btn_guardar")
        self.horizontalLayout_2.addWidget(self.btn_guardar)
        self.btn_eliminar = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_eliminar.setObjectName("btn_eliminar")
        self.horizontalLayout_2.addWidget(self.btn_eliminar)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Agenada"))
        self.lbl_nombre.setText(_translate("MainWindow", "Nombre:"))
        self.lbl_apellido.setText(_translate("MainWindow", "Apellido:"))
        self.lbl_mail.setText(_translate("MainWindow", "e-mail:"))
        self.btn_agregar.setText(_translate("MainWindow", "Agregar"))
        self.btn_carga.setText(_translate("MainWindow", "Carga"))
        self.btn_guardar.setText(_translate("MainWindow", "Guardar"))
        self.btn_eliminar.setText(_translate("MainWindow", "Elimina"))
