# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Usuario\Desktop\primer_proyecto\PyQt5\radioboton\radioboton.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(320, 264)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.rb_opcion1 = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_opcion1.setGeometry(QtCore.QRect(40, 40, 82, 17))
        self.rb_opcion1.setObjectName("rb_opcion1")
        self.rb_opcion2 = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_opcion2.setGeometry(QtCore.QRect(40, 70, 82, 17))
        self.rb_opcion2.setObjectName("rb_opcion2")
        self.rb_opcion3 = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_opcion3.setGeometry(QtCore.QRect(40, 100, 82, 17))
        self.rb_opcion3.setObjectName("rb_opcion3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 111, 16))
        self.label.setObjectName("label")
        self.btn_aceptar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_aceptar.setGeometry(QtCore.QRect(90, 190, 141, 31))
        self.btn_aceptar.setObjectName("btn_aceptar")
        self.mensaje = QtWidgets.QLabel(self.centralwidget)
        self.mensaje.setGeometry(QtCore.QRect(20, 140, 281, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.mensaje.setFont(font)
        self.mensaje.setText("")
        self.mensaje.setObjectName("mensaje")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 320, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.rb_opcion1.setText(_translate("MainWindow", "opcion 1"))
        self.rb_opcion2.setText(_translate("MainWindow", "opcion 2"))
        self.rb_opcion3.setText(_translate("MainWindow", "opcion 3"))
        self.label.setText(_translate("MainWindow", "Elija  una opcion"))
        self.btn_aceptar.setText(_translate("MainWindow", "Aceptar"))
