# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Usuario\Desktop\primer_proyecto\PyQt5\radioboton\radioboton_combinado.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(367, 468)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 20, 161, 21))
        self.label.setObjectName("label")
        self.num = QtWidgets.QGroupBox(self.centralwidget)
        self.num.setGeometry(QtCore.QRect(30, 50, 311, 111))
        self.num.setObjectName("num")
        self.op3 = QtWidgets.QRadioButton(self.num)
        self.op3.setGeometry(QtCore.QRect(20, 80, 82, 17))
        self.op3.setObjectName("op3")
        self.op1 = QtWidgets.QRadioButton(self.num)
        self.op1.setGeometry(QtCore.QRect(20, 20, 82, 17))
        self.op1.setObjectName("op1")
        self.op2 = QtWidgets.QRadioButton(self.num)
        self.op2.setGeometry(QtCore.QRect(20, 50, 82, 17))
        self.op2.setObjectName("op2")
        self.btn_aceptar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_aceptar.setGeometry(QtCore.QRect(220, 380, 131, 41))
        self.btn_aceptar.setObjectName("btn_aceptar")
        self.mensaje_dos = QtWidgets.QLabel(self.centralwidget)
        self.mensaje_dos.setGeometry(QtCore.QRect(130, 190, 221, 171))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.mensaje_dos.setFont(font)
        self.mensaje_dos.setText("")
        self.mensaje_dos.setAlignment(QtCore.Qt.AlignCenter)
        self.mensaje_dos.setObjectName("mensaje_dos")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 170, 161, 21))
        self.label_2.setObjectName("label_2")
        self.rd_opcionB = QtWidgets.QRadioButton(self.centralwidget)
        self.rd_opcionB.setGeometry(QtCore.QRect(50, 240, 82, 17))
        self.rd_opcionB.setObjectName("rd_opcionB")
        self.rd_opcionC = QtWidgets.QRadioButton(self.centralwidget)
        self.rd_opcionC.setGeometry(QtCore.QRect(50, 270, 82, 17))
        self.rd_opcionC.setObjectName("rd_opcionC")
        self.rd_opcionA = QtWidgets.QRadioButton(self.centralwidget)
        self.rd_opcionA.setGeometry(QtCore.QRect(50, 210, 82, 17))
        self.rd_opcionA.setObjectName("rd_opcionA")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 367, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Elija una opcion numerada"))
        self.num.setTitle(_translate("MainWindow", "Grupo Numerado"))
        self.op3.setText(_translate("MainWindow", "opcion 3"))
        self.op1.setText(_translate("MainWindow", "opcion 1"))
        self.op2.setText(_translate("MainWindow", "opcion 2"))
        self.btn_aceptar.setText(_translate("MainWindow", "Aceptar"))
        self.label_2.setText(_translate("MainWindow", "Elija una opcion de letras"))
        self.rd_opcionB.setText(_translate("MainWindow", "opcion B"))
        self.rd_opcionC.setText(_translate("MainWindow", "opcion C"))
        self.rd_opcionA.setText(_translate("MainWindow", "opcion A"))
