# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Usuario\Desktop\primer_proyecto\PyQt5\Tablas\01_tabla_formulario.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(760, 132)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabla = QtWidgets.QTableWidget(self.centralwidget)
        self.tabla.setGeometry(QtCore.QRect(10, 10, 461, 111))
        self.tabla.setObjectName("tabla")
        self.tabla.setColumnCount(3)
        self.tabla.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabla.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla.setHorizontalHeaderItem(2, item)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(490, 10, 261, 111))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.txt_nombre = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.txt_nombre.setObjectName("txt_nombre")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txt_nombre)
        self.lbl_apellido = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_apellido.setObjectName("lbl_apellido")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbl_apellido)
        self.txt_apellido = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.txt_apellido.setObjectName("txt_apellido")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txt_apellido)
        self.lbl_mail = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_mail.setObjectName("lbl_mail")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lbl_mail)
        self.txt_e_mail = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.txt_e_mail.setObjectName("txt_e_mail")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txt_e_mail)
        self.lbl_nombre = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_nombre.setObjectName("lbl_nombre")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_nombre)
        self.verticalLayout_7.addLayout(self.formLayout)
        self.btn_agregar = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_agregar.setObjectName("btn_agregar")
        self.verticalLayout_7.addWidget(self.btn_agregar)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.tabla.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nombre"))
        item = self.tabla.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Apellido"))
        item = self.tabla.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "e-mail"))
        self.lbl_apellido.setText(_translate("MainWindow", "Apellido:"))
        self.lbl_mail.setText(_translate("MainWindow", "e-mail:"))
        self.lbl_nombre.setText(_translate("MainWindow", "Nombre:"))
        self.btn_agregar.setText(_translate("MainWindow", "Agregar"))
